### ISSUE TITLE
Instruct to compile at src level if using ln -s 

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-docker#23]
```
kati@LAPTOP-D2GA3D2E:/mnt/c/Users/katil/Code/Github/PhysObjectExtractorTool/PhysObjectExtractor$ cd ..
kati@LAPTOP-D2GA3D2E:/mnt/c/Users/katil/Code/Github/PhysObjectExtractorTool$ docker run -it --name my_od -P -p 5901:5901 -p 6080:6080 -v ${PWD}:/home/cmsusr/PhysObjectEx
tractorTool cmsopendata/cmssw_5_3_32_vnc:latest /bin/bash
Setting up CMSSW_5_3_32
CMSSW should now be available.
[10:28:05] cmsusr@33646724634a ~/CMSSW_5_3_32/src $ ln -s ~/PhysObjectExtractorTool/
[10:29:50] cmsusr@33646724634a ~/CMSSW_5_3_32/src $ cd PhysObjectExtractorTool/
[10:29:54] cmsusr@33646724634a ~/CMSSW_5_3_32/src/PhysObjectExtractorTool $ cd PhysObjectExtractor/
[10:37:39] cmsusr@33646724634a ~/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor $ scram b
SCRAM fatal: Unable to locate the top of local release. Please run this command from a SCRAM-based area.
```

but compiling at the higher level works:

```
[11:47:36] cmsusr@33646724634a ~/CMSSW_5_3_32/src $ scram b
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Building CMSSW version CMSSW_5_3_32 ----
>> Entering Package PhysObjectExtractorTool/PhysObjectExtractor
>> Creating project symlinks
Entering library rule at PhysObjectExtractorTool/PhysObjectExtractor
>> Compiling edm plugin /home/cmsusr/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/ElectronAnalyzer.cc
>> Compiling edm plugin /home/cmsusr/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/EventAnalyzer.cc
>> Compiling edm plugin /home/cmsusr/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/JetAnalyzer.cc
[ ... ]

```

**Comment by caredg** [comment]
I am not sure what is this about.  We do not have any soft links in this lesson.  The compilation where it is instructed works fine.  Now, doing something like this:
`[10:28:05] cmsusr@33646724634a ~/CMSSW_5_3_32/src $ ln -s ~/PhysObjectExtractorTool/`
means that the package was cloned at `/home/cmsusr` level, which is not supposed to happen.  We never instruct to do this and so no additional instructions for soft links are needed.  Scraming at any level inside the package seems to work fine.

**Comment by caredg** [comment]
Ok, my bad. After reviewing the docker lesson I see now where this is mentioned:
https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/03-docker-for-cms-opendata/index.html#docker-container

I personally think this is way too much, but I am probably underestimating complications.  I am reopening this issue in any case...

Is this needed if people do not need to push to a repository from the host machine?

**Comment by caredg** [comment]
Ok, this is not really an issue that belongs to this lesson, but may appear in later lessons like where we clone some repository from Github.  Up to the cmssw lesson we work with the Demo version of the analyzer, which is created from scratch so there should be no conflicts. I will reference this issue to the the introtrigger lesson to make a note about this

**Comment by caredg** [comment]
This should be addressed in cms-opendata-workshop/workshop2021-lesson-introtrigger#1 and subsequent examples, perhaps.
