### ISSUE TITLE
Windows Firewall issue

### ISSUE THREAD

**Issue by apetkovi1** [cms-opendata-workshop/workshop2021-lesson-docker#30]
For Windows users there might be a problem when trying to set up a graphical interface while following instructions on https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/03-docker-for-cms-opendata/index.html. It seems that Windows Firewall is blocking these features. To enable them go to Windows Firewall->Advanced settings->Inbound rules->New rule. Then select ports and type 5900-5902 (that interval should cover it, mine port was 5901):
![ports](https://user-images.githubusercontent.com/72497935/121347452-80fe7780-c927-11eb-87c9-929c6e8c124f.PNG).
Go Next->Allow connection->Next, then name the rule. Having done that, go to Windows Firewall->Allow an app through firewall->Change settings and mark the TigerVNC (or some other viewer that you are using). It should look like this:
![Screenshot (10)](https://user-images.githubusercontent.com/72497935/121348976-4c8bbb00-c929-11eb-9056-532e34cc6f5a.png) Now, you should be able to view graphical interface.

**Comment by caredg** [comment]
Hi @katilp and @apetkovi1, is this something still pending? If yes, could you update the `od_instructions_source.md` file?

**Comment by katilp** [comment]
Maybe it would be best to post this on https://opendata-forum.cern.ch/ and link to it. We'll take care of that and add a link to it in the Windows part.
