### ISSUE TITLE
Move copy-paste instructions to the OS-dependent part

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-docker#31]
The [testing](https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html) episode of the last workshop docker tutorial included some copy-pasting instructions. @mattbellis do you remember if what was added as "IMPORTANT NOTE: " last time was for Windows users?

If they are still needed, they can be moved under the OS-dependent part of [the current episode 3](https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/03-docker-for-cms-opendata/index.html)
It already contains the instructions for VNC viewer and Windows.

**Comment by katilp** [comment]
I've removed those instructions in what is now the last section: https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/04-validation/index.html

**Comment by mattbellis** [comment]
@katilp That important note (shift-ctrl-v) is something that _I_ often have to do on Linux. I often have to tell Mac-using students in class that they may have to do that as well on their systems, but I can't remember if it's uniform. I think that's why I used the text "Depending on your system..."

**Comment by katilp** [comment]
OK, thanks, good to know. I'll add it then to the OS-dependent part of the previous section. We can then update the Mac part once someone goes through it.

For the sake of clarity, we should aim to have all copy-paste-edit details in a single place (with these 3 tabs that we have now)
