### ISSUE TITLE
Condition data caching does not happen

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-docker#34]
If the job accesses the condition data from frontier servers, the example demo code in https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/04-validation/index.html does not cache any data even if the global tag part is added to the config file.

Therefore, I would suggest removing it from here and making point of it when relevant, e.g. in the trigger pre-exercise @caredg 
let me know if OK and I'll remove (what remains of) it here.

**Comment by caredg** [comment]
Yes, let's remove it.  I will do the same with the VM tutorial

**Comment by katilp** [comment]
For the VM, it could actually cache something as in VM one needs to read the condition data from cvmfs. Having these two different is really not ideal, and we need to find a solution for this. 

If it were just for the jets, we have a simple solution already, i.e. extract the needed tables in a separate job. Do you know if something similar could be done for the trigger values? Are the values from condition data needed runtime, or just afterwards for luminosity evaluation?

**Comment by caredg** [comment]
Removed the GT part altogether.  Not needed for validating this
