### ISSUE TITLE
02 - docker container commands

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-docker#36]
For the sake of consistency, as `docker ps -a` and `docker rm <container>` commands are used in [03](https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/03-docker-for-cms-opendata/index.html), add them also as alternatives to `docker container ls -a` and `docker container rm <container>`  in the cheat sheet in [02](https://cms-opendata-workshop.github.io/workshop2021-lesson-docker/02-installing-docker/index.html).

**Comment by caredg** [comment]
done
